# Generated by Django 4.2 on 2025-02-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skinapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="account_locked_until",
        ),
        migrations.RemoveField(
            model_name="client",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="client",
            name="failed_login_attempts",
        ),
        migrations.RemoveField(
            model_name="client",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="client",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="client",
            name="social_id",
        ),
        migrations.RemoveField(
            model_name="client",
            name="social_provider",
        ),
        migrations.RemoveField(
            model_name="client",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(default="Not Provided", max_length=15),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="password",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name="client",
            table=None,
        ),
    ]
