# Generated by Django 4.2 on 2025-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skinapp", "0002_remove_client_account_locked_until_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("service", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="client",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
