# Generated by Django 4.2 on 2025-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skinapp", "0003_appointment_alter_client_password_alter_client_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
