# Generated by Django 4.2 on 2025-02-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skinapp", "0004_alter_appointment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("Skin Consultation", "Skin Consultation"),
                    ("Acne Treatment", "Acne Treatment"),
                    ("Laser Therapy", "Laser Therapy"),
                    ("Anti-Aging Solutions", "Anti-Aging Solutions"),
                ],
                max_length=50,
            ),
        ),
    ]
